# Generated by Django 5.2.10 on 2026-02-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_stripe_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
