# Generated by Django 5.2.10 on 2026-02-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userlibrary_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
