# Generated by Django 5.2.10 on 2026-02-03 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_stripe_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlibrary',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
