# Generated by Django 5.2.10 on 2026-01-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='content_url',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
